"""Initial database schema

Revision ID: 5c2128ef7c0c
Revises: 
Create Date: 2025-10-30 02:47:22.492580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2128ef7c0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('tenders_found', sa.Integer(), nullable=True),
    sa.Column('tenders_scraped', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_logs_id'), 'scrape_logs', ['id'], unique=False)
    op.create_index(op.f('ix_scrape_logs_run_date'), 'scrape_logs', ['run_date'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('notice_number', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('work_name', sa.Text(), nullable=True),
    sa.Column('tender_value', sa.String(length=50), nullable=True),
    sa.Column('published_date', sa.String(length=50), nullable=True),
    sa.Column('bid_start_date', sa.String(length=50), nullable=True),
    sa.Column('bid_close_date', sa.String(length=50), nullable=True),
    sa.Column('detail_url', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_bid_close_date'), 'tenders', ['bid_close_date'], unique=False)
    op.create_index(op.f('ix_tenders_id'), 'tenders', ['id'], unique=False)
    op.create_index(op.f('ix_tenders_published_date'), 'tenders', ['published_date'], unique=False)
    op.create_index(op.f('ix_tenders_tender_id'), 'tenders', ['tender_id'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('download_status', sa.String(length=50), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.tender_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('tender_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.String(length=100), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('general_terms', sa.Text(), nullable=True),
    sa.Column('legal_terms', sa.Text(), nullable=True),
    sa.Column('technical_terms', sa.Text(), nullable=True),
    sa.Column('submission_procedure', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.tender_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id')
    )
    op.create_index(op.f('ix_tender_details_id'), 'tender_details', ['id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.String(length=100), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('field_type', sa.String(length=50), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.tender_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_id'), 'extracted_fields', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_fields_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_tender_details_id'), table_name='tender_details')
    op.drop_table('tender_details')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_tenders_tender_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_published_date'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_bid_close_date'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_scrape_logs_run_date'), table_name='scrape_logs')
    op.drop_index(op.f('ix_scrape_logs_id'), table_name='scrape_logs')
    op.drop_table('scrape_logs')
    # ### end Alembic commands ###
