name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Lint with ruff
      run: |
        pip install ruff
        ruff check src/ tests/ --output-format=github
      continue-on-error: true
      
    - name: Type check with mypy
      run: |
        pip install mypy
        mypy src/ --ignore-missing-imports
      continue-on-error: true
      
    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --tb=short --cov=src --cov-report=term-missing
      continue-on-error: false
      
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v --tb=short
      continue-on-error: true
      env:
        TEST_MODE: ci

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Run Bandit Security Scan
      run: |
        pip install bandit[toml]
        bandit -r src/ -f json -o bandit-report.json
      continue-on-error: true
      
    - name: Run Safety Check
      run: |
        pip install safety
        safety check --json
      continue-on-error: true
      
    - name: Scan for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          warn-on-severity: moderate

